version: 2

models:
  - name: fact_orders
    description: "Fakta transaksi order (grain: 1 row = 1 order detail)"
    columns:
      - name: order_date
        description: "Tanggal order"
        tests:
          - not_null
      - name: customer_id
        description: "ID customer yang melakukan order"
        tests:
          - not_null
      - name: sales_amount
        description: "Nilai penjualan"
  
  - name: dim_customer
    description: "Dimensi customer dengan atribut demografi & perilaku login"
    columns:
      - name: customer_id
        description: "Unique identifier buat customer"
        tests:
          - not_null
          - unique